apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-pfl-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-pfl
  template:
    metadata:
      labels:
        app: db-pfl
    spec:
      containers:
      - name: db-pfl-container
        image: jatin1008/db-pfl
        ports:
        - containerPort: 4000
        env:
        - name: DATABASE_URL
          value: "mysql://avnadmin:AVNS_8P_iCQjlNFRvPDgF0Ww@mysql-80a953-jatinkumar10082003-0747.a.aivencloud.com:16093/defaultdb?ssl-mode=REQUIRED"
        - name: PORT
          value: "4000"
        - name: ROUNDS
          value: "11"
        - name: SECRET
          value: "1011"
---
apiVersion: v1
kind: Service
metadata:
  name: db-pfl-service
spec:
  selector:
    app: db-pfl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
  type: LoadBalancer
